export interface EffectDoc {
  name: string;
  signature: string;
  summary: string;
  range?: string;
  example?: string;
  category: 'filter' | 'dynamics' | 'spatial' | 'modulation' | 'envelope' | 'distortion' | 'pitch';
  aliases?: string[];
}

export const EFFECTS: EffectDoc[] = [
  {
    name: 'lpf',
    category: 'filter',
    signature: '.lpf(hz)',
    summary: 'Low-pass filter. Cutoff in Hz.',
    range: '20–20000 (typical 200–8000)',
    example: '.lpf(sine.range(500, 4000).slow(4))',
    aliases: ['cutoff', 'ctf', 'lp'],
  },
  {
    name: 'lpq',
    category: 'filter',
    signature: '.lpq(q)',
    summary: 'Low-pass resonance / Q factor. Above 30 the filter self-oscillates, classic for acid bass. Typical musical range 2-15.',
    range: '0-50 (typical 0-15, >30 = self-oscillation)',
    aliases: ['resonance'],
  },
  {
    name: 'hpf',
    category: 'filter',
    signature: '.hpf(hz)',
    summary: 'High-pass filter. Cutoff in Hz.',
    range: '20–20000',
    aliases: ['hp', 'hcutoff'],
  },
  {
    name: 'hpq',
    category: 'filter',
    signature: '.hpq(q)',
    summary: 'Resonance for the high-pass filter.',
    range: '0–30',
    aliases: ['hresonance'],
  },
  {
    name: 'bpf',
    category: 'filter',
    signature: '.bpf(hz)',
    summary: 'Band-pass filter.',
    range: '20–20000',
    aliases: ['bp', 'bandf'],
  },
  {
    name: 'bpq',
    category: 'filter',
    signature: '.bpq(q)',
    summary: 'Resonance for the band-pass filter.',
    aliases: ['bandq'],
  },
  {
    name: 'vowel',
    category: 'filter',
    signature: '.vowel(v)',
    summary: 'Formant/vowel filter. Accepts "a", "e", "i", "o", "u" in a pattern.',
    example: '.vowel("<a e i o>")',
  },
  // Change 2.1: filter envelope controls
  {
    name: 'lpenv',
    category: 'filter',
    signature: '.lpenv(depth)',
    summary: 'Lowpass filter envelope depth in semitones/cents. Positive pushes cutoff UP during the envelope; negative pulls it down. Pair with .lpa/.lpd to shape.',
    range: '-12 to 12 (typical -4 to 8)',
    example: '.lpenv(4)',
    aliases: ['lpe'],
  },
  {
    name: 'lpa',
    category: 'filter',
    signature: '.lpa(seconds)',
    summary: 'Lowpass envelope attack time in seconds.',
    range: '0-5',
    example: '.lpa(.1)',
    aliases: ['lpattack'],
  },
  {
    name: 'lpd',
    category: 'filter',
    signature: '.lpd(seconds)',
    summary: 'Lowpass envelope decay time.',
    range: '0-5',
    aliases: ['lpdecay'],
  },
  {
    name: 'lps',
    category: 'filter',
    signature: '.lps(level)',
    summary: 'Lowpass envelope sustain level.',
    range: '0-1',
    aliases: ['lpsustain'],
  },
  {
    name: 'lpr',
    category: 'filter',
    signature: '.lpr(seconds)',
    summary: 'Lowpass envelope release time.',
    range: '0-5',
    aliases: ['lprelease'],
  },
  {
    name: 'hpenv',
    category: 'filter',
    signature: '.hpenv(depth)',
    summary: 'Highpass filter envelope depth in semitones/cents. Positive pushes cutoff UP during the envelope; negative pulls it down. Pair with .hpa/.hpd to shape.',
    range: '-12 to 12 (typical -4 to 8)',
    aliases: ['hpe'],
  },
  {
    name: 'hpa',
    category: 'filter',
    signature: '.hpa(seconds)',
    summary: 'Highpass envelope attack time in seconds.',
    range: '0-5',
    aliases: ['hpattack'],
  },
  {
    name: 'hpd',
    category: 'filter',
    signature: '.hpd(seconds)',
    summary: 'Highpass envelope decay time.',
    range: '0-5',
    aliases: ['hpdecay'],
  },
  {
    name: 'hps',
    category: 'filter',
    signature: '.hps(level)',
    summary: 'Highpass envelope sustain level.',
    range: '0-1',
    aliases: ['hpsustain'],
  },
  {
    name: 'hpr',
    category: 'filter',
    signature: '.hpr(seconds)',
    summary: 'Highpass envelope release time.',
    range: '0-5',
    aliases: ['hprelease'],
  },
  {
    name: 'bpenv',
    category: 'filter',
    signature: '.bpenv(depth)',
    summary: 'Bandpass filter envelope depth in semitones/cents. Positive pushes cutoff UP during the envelope; negative pulls it down. Pair with .bpa/.bpd to shape.',
    range: '-12 to 12 (typical -4 to 8)',
    aliases: ['bpe'],
  },
  {
    name: 'bpa',
    category: 'filter',
    signature: '.bpa(seconds)',
    summary: 'Bandpass envelope attack time in seconds.',
    range: '0-5',
    aliases: ['bpattack'],
  },
  {
    name: 'bpd',
    category: 'filter',
    signature: '.bpd(seconds)',
    summary: 'Bandpass envelope decay time.',
    range: '0-5',
    aliases: ['bpdecay'],
  },
  {
    name: 'bps',
    category: 'filter',
    signature: '.bps(level)',
    summary: 'Bandpass envelope sustain level.',
    range: '0-1',
    aliases: ['bpsustain'],
  },
  {
    name: 'bpr',
    category: 'filter',
    signature: '.bpr(seconds)',
    summary: 'Bandpass envelope release time.',
    range: '0-5',
    aliases: ['bprelease'],
  },
  {
    name: 'ftype',
    category: 'filter',
    signature: '.ftype(type)',
    summary: "Filter type: '12db' (default), '24db', or 'ladder' (aggressive Moog-style).",
    example: '.ftype("ladder")',
  },
  {
    name: 'djf',
    category: 'filter',
    signature: '.djf(pos)',
    summary: 'DJ filter: 0.5 = flat, below = lowpass (deeper sweep), above = highpass. Classic DJ cue-sweep effect.',
    range: '0-1',
    example: '.djf(sine.range(0,1).slow(8))',
  },
  {
    name: 'gain',
    category: 'dynamics',
    signature: '.gain(amount)',
    summary: 'Volume. Patternable.',
    range: '0–1.5',
    example: '.gain("[.5 1]*4")',
  },
  {
    name: 'velocity',
    category: 'dynamics',
    signature: '.velocity(v)',
    summary: 'Note velocity (MIDI-style).',
    range: '0–1',
  },
  // Change 2.2: dynamics and orbit
  {
    name: 'orbit',
    category: 'spatial',
    signature: '.orbit(n)',
    summary: 'Routing bus. Patterns with the same orbit number share a send/return path, so global effects (room, delay) are not additive across voices. Use different orbits for drums and bass to keep reverbs clean.',
    range: '0-15',
    aliases: ['o'],
    example: '.orbit(1)',
  },
  {
    name: 'duckorbit',
    category: 'dynamics',
    signature: '.duckorbit(n)',
    summary: 'Target orbit(s) to duck when this pattern plays. Core sidechain idiom: a kick at orbit(0).duckorbit(1) pumps everything on orbit 1.',
    aliases: ['duck'],
    example: '.duckorbit(1)',
  },
  {
    name: 'duckattack',
    category: 'dynamics',
    signature: '.duckattack(seconds)',
    summary: 'Time for the ducked orbit to return to full volume after a duck trigger. Small values (.05-.2) give tight pumping; larger values stretch the envelope.',
    range: '0.02-1',
    aliases: ['duckatt', 'datt'],
  },
  {
    name: 'duckdepth',
    category: 'dynamics',
    signature: '.duckdepth(amount)',
    summary: 'How deep the duck goes. 0 = no ducking, 1 = silent during trigger. Classic house settings: .8-.95.',
    range: '0-1',
  },
  {
    name: 'compressor',
    category: 'dynamics',
    signature: '.compressor(spec)',
    summary: "Compressor. Compact form: 'threshold:ratio:knee:attack:release'. Good starting point for glue: '-20:4:10:.003:.1'.",
    example: '.compressor("-20:4:10:.003:.1")',
  },
  {
    name: 'postgain',
    category: 'dynamics',
    signature: '.postgain(n)',
    summary: 'Linear gain applied AFTER all effects. Use to compensate for loudness changes after distort/compressor.',
    range: '0-4',
  },
  {
    name: 'pan',
    category: 'spatial',
    signature: '.pan(pos)',
    summary: 'Stereo position. 0 = left, 0.5 = center, 1 = right.',
    range: '0–1',
    example: '.pan(sine.range(0, 1).slow(4))',
  },
  {
    name: 'room',
    category: 'spatial',
    signature: '.room(wet)',
    summary: 'Reverb wet amount.',
    range: '0–1 (can go higher)',
  },
  {
    name: 'roomsize',
    aliases: ['size'],
    category: 'spatial',
    signature: '.roomsize(size)',
    summary: 'Reverb size/decay. Also aliased as .size().',
    range: '0–10',
  },
  {
    name: 'delay',
    category: 'spatial',
    signature: '.delay(wet) or .delay("wet:time:feedback")',
    summary: 'Delay effect. Compact form packs wet, time, feedback.',
    range: '0–1 for wet/feedback',
    example: '.delay(".8:.125:.6")',
  },
  {
    name: 'delaytime',
    category: 'spatial',
    signature: '.delaytime(t)',
    summary: 'Delay time in cycles.',
    range: '0–2',
  },
  {
    name: 'delayfeedback',
    category: 'spatial',
    signature: '.delayfeedback(amount)',
    summary: 'Delay feedback amount.',
    range: '0–1 (>.95 → runaway)',
    aliases: ['dfb'],
  },
  // Change 2.3: reverb/delay extras
  {
    name: 'roomlp',
    category: 'spatial',
    signature: '.roomlp(hz)',
    summary: 'Lowpass cutoff on the reverb send. Use to pre-darken reverb so it does not clash with the mix.',
    range: '200-20000',
    aliases: ['rlp'],
    example: '.room(.6).roomlp(4000)',
  },
  {
    name: 'roomdim',
    category: 'spatial',
    signature: '.roomdim(hz)',
    summary: 'Reverb high-frequency damping. Frequency at which the reverb tail drops -60dB.',
    aliases: ['rdim'],
  },
  {
    name: 'roomfade',
    category: 'spatial',
    signature: '.roomfade(seconds)',
    summary: 'Reverb fade/tail time in seconds.',
    aliases: ['rfade'],
  },
  {
    name: 'iresponse',
    category: 'spatial',
    signature: '.iresponse(sample)',
    summary: 'Use a sample as the impulse response for convolution reverb — great for realistic spaces.',
    aliases: ['ir'],
  },
  {
    name: 'delaysync',
    category: 'spatial',
    signature: '.delaysync(cycles)',
    summary: 'Tempo-synced delay time in cycles instead of seconds. 1/8 = 8th-note delay.',
    aliases: ['delays', 'ds'],
    example: '.delay(.6).delaysync(3/16)',
  },
  {
    name: 'phaser',
    category: 'modulation',
    signature: '.phaser(rate)',
    summary: 'Phaser effect.',
    range: '0–10',
  },
  {
    name: 'tremolo',
    category: 'modulation',
    signature: '.tremolo(rate)',
    summary: 'Amplitude modulation tremolo.',
  },
  {
    name: 'vibrato',
    category: 'modulation',
    signature: '.vibrato(rate)',
    summary: 'Pitch modulation vibrato.',
  },
  // Change 2.4: modulation controls
  {
    name: 'phaserdepth',
    category: 'modulation',
    signature: '.phaserdepth(amount)',
    summary: 'Phaser depth. 0 = inaudible, 1 = fully wet.',
    range: '0-1 (default .75)',
    aliases: ['phd'],
  },
  {
    name: 'phasercenter',
    category: 'modulation',
    signature: '.phasercenter(hz)',
    summary: 'Phaser center frequency in Hz.',
    range: '100-4000 (default 1000)',
    aliases: ['phc'],
  },
  {
    name: 'phasersweep',
    category: 'modulation',
    signature: '.phasersweep(hz)',
    summary: 'Phaser LFO sweep range in Hz around center.',
    range: '0-4000 (default 2000)',
    aliases: ['phs'],
  },
  {
    name: 'tremolosync',
    category: 'modulation',
    signature: '.tremolosync(cycles)',
    summary: 'Tempo-synced tremolo rate in cycles.',
    aliases: ['tremsync'],
  },
  {
    name: 'tremolodepth',
    category: 'modulation',
    signature: '.tremolodepth(amount)',
    summary: 'Tremolo modulation depth. 0 = no effect, 1 = full amplitude swing.',
    range: '0-1',
    aliases: ['tremdepth'],
  },
  {
    name: 'tremoloshape',
    category: 'modulation',
    signature: '.tremoloshape(type)',
    summary: "Tremolo waveshape: 'tri', 'sine', 'square', 'saw', 'ramp'.",
    aliases: ['tremshape'],
  },
  {
    name: 'vib',
    category: 'modulation',
    signature: '.vib(hz)',
    summary: 'Vibrato LFO rate in Hz. Pair with .vibmod for depth.',
    aliases: ['v'],
    example: '.vib(4).vibmod(.5)',
  },
  {
    name: 'vibmod',
    category: 'modulation',
    signature: '.vibmod(semitones)',
    summary: 'Vibrato depth in semitones. Typical musical vibrato is .2-.5.',
    aliases: ['vmod'],
  },
  // Change 2.6: FM synth controls
  {
    name: 'fmattack',
    category: 'modulation',
    signature: '.fmattack(seconds)',
    summary: 'Time for FM modulation to reach full depth.',
    aliases: ['fmatt'],
  },
  {
    name: 'fmdecay',
    category: 'modulation',
    signature: '.fmdecay(seconds)',
    summary: 'FM modulation decay time.',
    aliases: ['fmdec'],
  },
  {
    name: 'fmsustain',
    category: 'modulation',
    signature: '.fmsustain(level)',
    summary: 'FM modulation sustain level.',
    range: '0-1',
    aliases: ['fmsus'],
  },
  {
    name: 'fmenv',
    category: 'modulation',
    signature: '.fmenv(type)',
    summary: "FM envelope curve: 'lin' or 'exp'.",
    aliases: ['fme'],
  },
  {
    name: 'shape',
    category: 'distortion',
    signature: '.shape(amount)',
    summary: 'Waveshaping distortion.',
    range: '0–1',
  },
  {
    name: 'distort',
    category: 'distortion',
    signature: '.distort(amount)',
    summary: 'Distortion amount.',
    range: '0–1',
  },
  {
    name: 'crush',
    category: 'distortion',
    signature: '.crush(bits)',
    summary: 'Bitcrusher. Lower bits = more crunch.',
    range: '1–16',
  },
  {
    name: 'coarse',
    category: 'distortion',
    signature: '.coarse(n)',
    summary: 'Sample-rate reduction.',
  },
  // Change 2.7: distortion type
  {
    name: 'distorttype',
    category: 'distortion',
    signature: '.distorttype(type)',
    summary: "Distortion algorithm: 'fold', 'chebyshev', 'scurve', 'diode', 'asym', 'sinefold'. Changes the character dramatically — try 'diode' for harmonic warmth, 'fold' for brutal wavefold.",
    aliases: ['disttype'],
    example: '.distort(.8).distorttype("fold")',
  },
  {
    name: 'distortvol',
    category: 'distortion',
    signature: '.distortvol(n)',
    summary: 'Post-gain compensation for distort. The fold/chebyshev types can get quiet at high amounts; use this to recover.',
    aliases: ['distvol'],
  },
  {
    name: 'attack',
    category: 'envelope',
    signature: '.attack(seconds)',
    summary: 'Envelope attack time.',
    range: '0–5',
  },
  {
    name: 'decay',
    category: 'envelope',
    signature: '.decay(seconds)',
    summary: 'Envelope decay time.',
  },
  {
    name: 'sustain',
    category: 'envelope',
    signature: '.sustain(level)',
    summary: 'Envelope sustain level.',
    range: '0–1',
  },
  {
    name: 'release',
    category: 'envelope',
    signature: '.release(seconds)',
    summary: 'Envelope release time.',
  },
  {
    name: 'adsr',
    category: 'envelope',
    signature: '.adsr("a:d:s:r")',
    summary: 'Compact ADSR shorthand.',
    example: '.adsr(".02:.1:.5:.3")',
  },
  // Change 2.5: pitch envelope
  {
    name: 'penv',
    category: 'envelope',
    signature: '.penv(semitones)',
    summary: 'Pitch envelope depth in semitones. Negative flips direction. Classic use: .penv(-24) on a kick for a descending pitch drop.',
    range: '-36 to 36',
    example: '.penv(-24).pdecay(.15)',
  },
  {
    name: 'pattack',
    category: 'envelope',
    signature: '.pattack(seconds)',
    summary: 'Pitch envelope attack time.',
    aliases: ['patt'],
  },
  {
    name: 'pdecay',
    category: 'envelope',
    signature: '.pdecay(seconds)',
    summary: 'Pitch envelope decay time.',
    aliases: ['pdec'],
  },
  {
    name: 'prelease',
    category: 'envelope',
    signature: '.prelease(seconds)',
    summary: 'Pitch envelope release time.',
    aliases: ['prel'],
  },
  {
    name: 'pcurve',
    category: 'envelope',
    signature: '.pcurve(type)',
    summary: 'Pitch envelope curve: 0 = linear, 1 = exponential.',
    range: '0-1',
  },
  {
    name: 'panchor',
    category: 'envelope',
    signature: '.panchor(pos)',
    summary: 'Pitch envelope direction anchor. 0 = envelope above note, 1 = below.',
    range: '0-1',
  },
  {
    name: 'speed',
    category: 'pitch',
    signature: '.speed(rate)',
    summary: 'Playback rate. Negative reverses the sample.',
    range: '-4–4',
  },
  {
    name: 'fm',
    category: 'modulation',
    signature: '.fm(index)',
    summary: 'FM modulation index (for the default FM synth voice).',
    range: '0–10',
  },
  {
    name: 'fmh',
    category: 'modulation',
    signature: '.fmh(harmonicity)',
    summary: 'FM harmonicity ratio.',
  },
  {
    name: 'begin',
    category: 'pitch',
    signature: '.begin(t)',
    summary: 'Start sample at fraction t (0–1).',
  },
  {
    name: 'end',
    category: 'pitch',
    signature: '.end(t)',
    summary: 'End sample at fraction t (0–1).',
  },
  {
    name: 'loop',
    category: 'pitch',
    signature: '.loop(n)',
    summary: 'Loop sample n times.',
  },
];

export function findEffect(name: string): EffectDoc | undefined {
  const lower = name.toLowerCase().replace(/^\./, '');
  return EFFECTS.find(
    (e) =>
      e.name.toLowerCase() === lower ||
      e.aliases?.some((a) => a.toLowerCase() === lower),
  );
}

export function effectsByCategory(category: EffectDoc['category']): EffectDoc[] {
  return EFFECTS.filter((e) => e.category === category);
}

export const EFFECT_NAMES: ReadonlySet<string> = new Set(
  EFFECTS.flatMap((e) => [e.name, ...(e.aliases ?? [])]),
);
