export interface SoundEntry {
  name: string;
  kind: 'drum' | 'bank' | 'gm' | 'synth' | 'sample' | 'vcsl' | 'dirt';
  description: string;
}

export const DRUMS: SoundEntry[] = [
  { name: 'bd', kind: 'drum', description: 'Bass drum / kick' },
  { name: 'sd', kind: 'drum', description: 'Snare drum' },
  { name: 'rim', kind: 'drum', description: 'Rimshot' },
  { name: 'cp', kind: 'drum', description: 'Clap' },
  { name: 'hh', kind: 'drum', description: 'Closed hi-hat' },
  { name: 'oh', kind: 'drum', description: 'Open hi-hat' },
  { name: 'rd', kind: 'drum', description: 'Ride cymbal' },
  { name: 'cr', kind: 'drum', description: 'Crash cymbal' },
  { name: 'lt', kind: 'drum', description: 'Low tom' },
  { name: 'mt', kind: 'drum', description: 'Mid tom' },
  { name: 'ht', kind: 'drum', description: 'High tom' },
  { name: 'cb', kind: 'drum', description: 'Cowbell' },
  { name: 'sh', kind: 'drum', description: 'Shaker' },
];

export const DRUM_BANKS: SoundEntry[] = [
  { name: 'RolandTR909', kind: 'bank', description: '909 house/techno kit — punchy kick, crisp snare' },
  { name: 'RolandTR808', kind: 'bank', description: '808 hip-hop kit — deep sub kick, snappy snare' },
  { name: 'RolandTR707', kind: 'bank', description: '707 pop/rock kit — cleaner acoustic-ish sounds' },
  { name: 'RolandTR505', kind: 'bank', description: '505 kit — lo-fi charm, rock/pop' },
  { name: 'AkaiLinn', kind: 'bank', description: 'Linn LM-1 style — classic 80s' },
  { name: 'RhythmAce', kind: 'bank', description: 'Ace Tone Rhythm Ace — early preset machine' },
  { name: 'ViscoSpaceDrum', kind: 'bank', description: 'Visco space drum — ambient/experimental' },
  { name: 'RolandCompurhythm1000', kind: 'bank', description: 'CR-1000 — vintage 80s rhythm machine' },
  { name: 'RolandTR606', kind: 'bank', description: '606 kit — tight, electronic, classic acid house' },
  { name: 'RolandTR727', kind: 'bank', description: '727 Latin percussion' },
  { name: 'LinnLM1', kind: 'bank', description: 'Linn LM-1 — Prince, MJ-era 80s' },
  { name: 'LinnDrum', kind: 'bank', description: 'LinnDrum — the 80s pop standard' },
  { name: 'AlesisHR16', kind: 'bank', description: 'Alesis HR-16 — late-80s to 90s, crunchy' },
  { name: 'OberheimDMX', kind: 'bank', description: 'DMX — Run-DMC, classic hip-hop' },
  { name: 'EmuSP12', kind: 'bank', description: 'E-mu SP-12 — golden-era hip-hop sampler drums' },
  { name: 'CasioRZ1', kind: 'bank', description: 'Casio RZ-1 — lo-fi 80s' },
  { name: 'YamahaRX5', kind: 'bank', description: 'Yamaha RX5 — FM-esque 80s' },
  { name: 'RolandCompurhythm78', kind: 'bank', description: 'CR-78 — the Pet Shop Boys preset machine' },
  { name: 'AJKPercusyn', kind: 'bank', description: 'AJK Percusyn — digital percussion synthesizer' },
  { name: 'AkaiMPC60', kind: 'bank', description: 'Akai MPC60 — golden-era hip-hop sampler' },
  { name: 'AkaiXR10', kind: 'bank', description: 'Akai XR10 — 16-bit drum machine' },
  { name: 'AlesisSR16', kind: 'bank', description: 'Alesis SR-16 — studio workhorse drum machine' },
  { name: 'BossDR110', kind: 'bank', description: 'Boss DR-110 — compact analog Dr. Rhythm' },
  { name: 'BossDR220', kind: 'bank', description: 'Boss DR-220 — digital 80s preset beats' },
  { name: 'BossDR55', kind: 'bank', description: 'Boss DR-55 — first Dr. Rhythm, raw analog' },
  { name: 'BossDR550', kind: 'bank', description: 'Boss DR-550 — 90s digital drum machine' },
  { name: 'BossDR660', kind: 'bank', description: 'Boss DR-660 — 90s PCM drum module' },
  { name: 'CasioSK1', kind: 'bank', description: 'Casio SK-1 — toy sampling keyboard, lo-fi' },
  { name: 'CasioVL1', kind: 'bank', description: 'Casio VL-1 — calculator-synth sounds' },
  { name: 'DoepferMS404', kind: 'bank', description: 'Doepfer MS-404 — analog monosynth percussion' },
  { name: 'EmuDrumulator', kind: 'bank', description: 'E-mu Drumulator — affordable 80s digital drums' },
  { name: 'EmuModular', kind: 'bank', description: 'E-mu Modular — modular synth percussion' },
  { name: 'KorgDDM110', kind: 'bank', description: 'Korg DDM-110 — SuperDrums, digital 80s' },
  { name: 'KorgKPR77', kind: 'bank', description: 'Korg KPR-77 — analog, Depeche Mode preset box' },
  { name: 'KorgKR55', kind: 'bank', description: 'Korg KR-55 — vintage 70s rhythm machine' },
  { name: 'KorgKRZ', kind: 'bank', description: 'Korg KRZ — rare rhythm box' },
  { name: 'KorgM1', kind: 'bank', description: 'Korg M1 — iconic 80s/90s workstation drums' },
  { name: 'KorgMinipops', kind: 'bank', description: 'Korg Minipops — classic 60s/70s rhythm box' },
  { name: 'KorgPoly800', kind: 'bank', description: 'Korg Poly-800 — 80s polysynth percussion' },
  { name: 'KorgT3', kind: 'bank', description: 'Korg T3 — workstation drums' },
  { name: 'Linn9000', kind: 'bank', description: 'Linn 9000 — successor to LinnDrum' },
  { name: 'LinnLM2', kind: 'bank', description: 'Linn LM-2 — refined LinnDrum variant' },
  { name: 'MFB512', kind: 'bank', description: 'MFB-512 — analog drum module' },
  { name: 'MPC1000', kind: 'bank', description: 'Akai MPC1000 — modern production standard' },
  { name: 'MoogConcertMateMG1', kind: 'bank', description: 'Moog ConcertMate MG-1 — Moog percussion' },
  { name: 'RhodesPolaris', kind: 'bank', description: 'Rhodes Polaris — synth with built-in drums' },
  { name: 'RolandCompurhythm8000', kind: 'bank', description: 'CR-8000 — analog, thicker than CR-78' },
  { name: 'RolandD110', kind: 'bank', description: 'Roland D-110 — LA synthesis drums' },
  { name: 'RolandD70', kind: 'bank', description: 'Roland D-70 — 90s workstation percussion' },
  { name: 'RolandDDR30', kind: 'bank', description: 'Roland DDR-30 — digital rhythm coach' },
  { name: 'RolandJD990', kind: 'bank', description: 'Roland JD-990 — supersaw-era synth drums' },
  { name: 'RolandMC202', kind: 'bank', description: 'Roland MC-202 — MicroComposer percussion' },
  { name: 'RolandMC303', kind: 'bank', description: 'Roland MC-303 — Groovebox, dance-focused' },
  { name: 'RolandMT32', kind: 'bank', description: 'Roland MT-32 — DOS-era synth module' },
  { name: 'RolandR8', kind: 'bank', description: 'Roland R-8 — 90s professional drum machine' },
  { name: 'RolandS50', kind: 'bank', description: 'Roland S-50 — early sampler percussion' },
  { name: 'RolandSH09', kind: 'bank', description: 'Roland SH-09 — analog monosynth percussion' },
  { name: 'RolandSystem100', kind: 'bank', description: 'Roland System-100 — modular analog percussion' },
  { name: 'RolandTR626', kind: 'bank', description: 'TR-626 — 80s digital, punchy PCM drums' },
  { name: 'SakataDPM48', kind: 'bank', description: 'Sakata DPM-48 — rare Japanese analog drums' },
  { name: 'SequentialCircuitsDrumtracks', kind: 'bank', description: 'Sequential Circuits Drumtraks — early digital' },
  { name: 'SequentialCircuitsTom', kind: 'bank', description: 'Sequential Circuits Tom — dedicated tom module' },
  { name: 'SergeModular', kind: 'bank', description: 'Serge Modular — West Coast percussion' },
  { name: 'SimmonsSDS400', kind: 'bank', description: 'Simmons SDS-400 — analog electronic drums' },
  { name: 'SimmonsSDS5', kind: 'bank', description: 'Simmons SDS-5 — hexagonal pad fame, 80s synth drums' },
  { name: 'SoundmastersR88', kind: 'bank', description: 'Soundmasters R-88 — budget analog drum box' },
  { name: 'UnivoxMicroRhythmer12', kind: 'bank', description: 'Univox Micro-Rhythmer 12 — lo-fi vintage' },
  { name: 'XdrumLM8953', kind: 'bank', description: 'X-Drum LM-8953 — analog percussion chip' },
  { name: 'YamahaRM50', kind: 'bank', description: 'Yamaha RM50 — 90s rackmount drum module' },
  { name: 'YamahaRY30', kind: 'bank', description: 'Yamaha RY30 — AWM2 synthesis drum machine' },
  { name: 'YamahaTG33', kind: 'bank', description: 'Yamaha TG33 — vector synthesis module' },
];

export const SYNTHS: SoundEntry[] = [
  { name: 'sine', kind: 'synth', description: 'Sine wave — also the basis for synthesized 808 kicks: note("c1").s("sine").decay(.5).sustain(0).shape(.3)' },
  { name: 'square', kind: 'synth', description: 'Square wave oscillator — good for sub bass layering' },
  { name: 'triangle', kind: 'synth', description: 'Triangle wave oscillator — softer sub bass' },
  { name: 'sawtooth', kind: 'synth', description: 'Sawtooth wave — classic for bass, leads, pads. Detune with .add(note("0,.1"))' },
  { name: 'white', kind: 'synth', description: 'White noise — use for synth hi-hats: s("white*16").decay(.02).sustain(0).hpf(7000)' },
  { name: 'pink', kind: 'synth', description: 'Pink noise — warmer noise, good for snare layers and risers' },
  { name: 'brown', kind: 'synth', description: 'Brown noise — deep rumble, use for sub-layer textures' },
  { name: 'fm', kind: 'synth', description: 'Default FM synth voice' },
  { name: 'supersaw', kind: 'synth', description: 'Layered supersaw' },
  { name: 'crackle', kind: 'synth', description: 'Subtle crackle noise (paired with .density)' },
  { name: 'z_sawtooth', kind: 'synth', description: 'ZZFX sawtooth variant' },
  { name: 'z_sine', kind: 'synth', description: 'ZZFX sine variant' },
  { name: 'z_square', kind: 'synth', description: 'ZZFX square variant' },
  { name: 'z_noise', kind: 'synth', description: 'ZZFX noise variant' },
  { name: 'wt_flute', kind: 'synth', description: 'Wavetable synth — flute shape' },
  { name: 'wt_dbass', kind: 'synth', description: 'Wavetable synth — detuned bass shape' },
];

export const SAMPLE_LIBRARIES: SoundEntry[] = [
  { name: 'piano', kind: 'sample', description: 'Grand piano samples' },
  { name: 'jazz', kind: 'sample', description: 'Jazz loop samples' },
  { name: 'metal', kind: 'sample', description: 'Metal hit samples' },
  { name: 'wind', kind: 'sample', description: 'Wind texture samples' },
  { name: 'insect', kind: 'sample', description: 'Insect field recordings' },
  { name: 'east', kind: 'sample', description: 'Eastern instruments' },
  { name: 'crow', kind: 'sample', description: 'Crow calls' },
  { name: 'space', kind: 'sample', description: 'Space texture samples' },
  { name: 'numbers', kind: 'sample', description: 'Spoken number samples' },
  { name: 'perc', kind: 'sample', description: 'General percussion' },
  { name: 'casio', kind: 'sample', description: 'Casio keyboard samples' },
  { name: 'amen', kind: 'sample', description: 'The Amen break (loaded via samples("github:yaxu/clean-breaks") or similar). Pair with .fit().chop(N).cut(1).' },
  { name: 'breaks', kind: 'sample', description: 'Breakbeat loops (needs samples() call).' },
  { name: 'crate', kind: 'sample', description: 'eddyflux/crate percussion kit (load with samples("github:eddyflux/crate").bank("crate"))' },
];

export const GM_INSTRUMENTS: SoundEntry[] = [
  { name: 'gm_acoustic_grand_piano', kind: 'gm', description: 'GM acoustic grand piano' },
  { name: 'gm_electric_piano_1', kind: 'gm', description: 'GM electric piano (Rhodes-like)' },
  { name: 'gm_acoustic_guitar_nylon', kind: 'gm', description: 'GM nylon acoustic guitar' },
  { name: 'gm_electric_guitar_muted', kind: 'gm', description: 'GM muted electric guitar' },
  { name: 'gm_overdriven_guitar', kind: 'gm', description: 'GM overdriven guitar' },
  { name: 'gm_acoustic_bass', kind: 'gm', description: 'GM acoustic bass' },
  { name: 'gm_electric_bass_finger', kind: 'gm', description: 'GM fingered electric bass' },
  { name: 'gm_synth_bass_1', kind: 'gm', description: 'GM synth bass 1' },
  { name: 'gm_synth_bass_2', kind: 'gm', description: 'GM synth bass 2' },
  { name: 'gm_synth_strings_1', kind: 'gm', description: 'GM synth strings 1' },
  { name: 'gm_string_ensemble_1', kind: 'gm', description: 'GM string ensemble' },
  { name: 'gm_voice_oohs', kind: 'gm', description: 'GM voice "oohs" pad' },
  { name: 'gm_choir_aahs', kind: 'gm', description: 'GM choir "aahs" pad' },
  { name: 'gm_blown_bottle', kind: 'gm', description: 'GM blown bottle' },
  { name: 'gm_lead_1_square', kind: 'gm', description: 'GM square lead' },
  { name: 'gm_lead_2_sawtooth', kind: 'gm', description: 'GM sawtooth lead' },
  { name: 'gm_pad_2_warm', kind: 'gm', description: 'GM warm pad' },
  { name: 'gm_pad_3_polysynth', kind: 'gm', description: 'GM polysynth pad' },
  { name: 'gm_epiano1', kind: 'gm', description: 'GM electric piano alias' },
  { name: 'gm_electric_guitar_clean', kind: 'gm', description: 'GM clean electric guitar — for arpeggios' },
  { name: 'gm_accordion', kind: 'gm', description: 'GM accordion' },
  { name: 'gm_xylophone', kind: 'gm', description: 'GM xylophone — arpeggio playground' },
  { name: 'gm_marimba', kind: 'gm', description: 'GM marimba' },
  { name: 'gm_vibraphone', kind: 'gm', description: 'GM vibraphone — jazz comping' },
  { name: 'gm_celesta', kind: 'gm', description: 'GM celesta — bell-like' },
  { name: 'gm_french_horn', kind: 'gm', description: 'GM french horn' },
  { name: 'gm_brass_section', kind: 'gm', description: 'GM brass section — stab horns' },
  { name: 'gm_trumpet', kind: 'gm', description: 'GM trumpet' },
  { name: 'gm_lead_6_voice', kind: 'gm', description: 'GM voice lead' },
  { name: 'gm_lead_8_bass_lead', kind: 'gm', description: 'GM bass lead' },
  { name: 'gm_pad_1_new_age', kind: 'gm', description: 'GM new age pad' },
  { name: 'gm_pad_4_choir', kind: 'gm', description: 'GM choir pad' },
  { name: 'gm_pad_5_bowed', kind: 'gm', description: 'GM bowed pad' },
  { name: 'gm_pad_7_halo', kind: 'gm', description: 'GM halo pad' },
  { name: 'gm_fx_1_rain', kind: 'gm', description: 'GM rain effect' },
  { name: 'gm_fx_4_atmosphere', kind: 'gm', description: 'GM atmosphere' },
  { name: 'gm_banjo', kind: 'gm', description: 'GM banjo' },
  { name: 'gm_acoustic_guitar_steel', kind: 'gm', description: 'GM steel acoustic guitar' },
  { name: 'gm_electric_guitar_jazz', kind: 'gm', description: 'GM jazz guitar — warm mellow tone' },
  { name: 'gm_percussive_organ', kind: 'gm', description: 'GM percussive organ — click attack' },
  { name: 'gm_drawbar_organ', kind: 'gm', description: 'GM drawbar organ — Hammond-style' },
  { name: 'gm_church_organ', kind: 'gm', description: 'GM church organ — sustained pipe organ' },
  { name: 'gm_fretless_bass', kind: 'gm', description: 'GM fretless bass — smooth singing tone' },
  { name: 'gm_electric_bass_pick', kind: 'gm', description: 'GM picked electric bass — punchy attack' },
  { name: 'gm_distortion_guitar', kind: 'gm', description: 'GM distortion guitar — heavy rock' },
  { name: 'gm_piccolo', kind: 'gm', description: 'GM piccolo — high-register woodwind' },
  { name: 'gm_oboe', kind: 'gm', description: 'GM oboe — double-reed orchestral' },
  { name: 'gm_pizzicato_strings', kind: 'gm', description: 'GM pizzicato strings — plucked orchestral' },
];

export const VCSL_INSTRUMENTS: SoundEntry[] = [
  { name: 'kawai', kind: 'vcsl', description: 'Kawai piano (default-loaded, no samples() needed)' },
  { name: 'steinway', kind: 'vcsl', description: 'Steinway piano (default-loaded)' },
  { name: 'snare_modern', kind: 'vcsl', description: 'Modern snare — cleaner than drum-machine snares' },
  { name: 'snare_hi', kind: 'vcsl', description: 'High-tuned snare' },
  { name: 'snare_low', kind: 'vcsl', description: 'Low-tuned snare' },
  { name: 'snare_rim', kind: 'vcsl', description: 'Snare rimshot' },
  { name: 'bassdrum1', kind: 'vcsl', description: 'Acoustic bass drum' },
  { name: 'bassdrum2', kind: 'vcsl', description: 'Acoustic bass drum alt' },
  { name: 'conga', kind: 'vcsl', description: 'Conga percussion — world/latin' },
  { name: 'bongo', kind: 'vcsl', description: 'Bongo percussion' },
  { name: 'darbuka', kind: 'vcsl', description: 'Darbuka — middle-eastern percussion' },
  { name: 'framedrum', kind: 'vcsl', description: 'Frame drum — textural percussion' },
  { name: 'timpani', kind: 'vcsl', description: 'Orchestral timpani' },
  { name: 'sax', kind: 'vcsl', description: 'Saxophone (chromatic, use with note())' },
  { name: 'sax_vib', kind: 'vcsl', description: 'Saxophone with vibrato' },
  { name: 'harmonica', kind: 'vcsl', description: 'Harmonica (chromatic)' },
  { name: 'harp', kind: 'vcsl', description: 'Harp — arpeggios and pads' },
  { name: 'folkharp', kind: 'vcsl', description: 'Folk harp — smaller, brighter' },
  { name: 'didgeridoo', kind: 'vcsl', description: 'Didgeridoo drone' },
  { name: 'ocarina', kind: 'vcsl', description: 'Ocarina — breathy, melodic' },
];

export const DIRT_SAMPLES: SoundEntry[] = [
  { name: 'clubkick', kind: 'dirt', description: 'Modern club kicks (load: samples("github:tidalcycles/dirt-samples"))' },
  { name: 'hardkick', kind: 'dirt', description: 'Hard electronic kicks' },
  { name: 'popkick', kind: 'dirt', description: 'Pop/modern kicks' },
  { name: 'reverbkick', kind: 'dirt', description: 'Reverb-tail kicks' },
  { name: 'future', kind: 'dirt', description: 'Future/modern electronic percussion and textures' },
  { name: 'techno', kind: 'dirt', description: 'Techno percussion and hits' },
  { name: 'house', kind: 'dirt', description: 'House-style percussion' },
  { name: 'rave', kind: 'dirt', description: 'Rave stabs and percussion' },
  { name: 'electro1', kind: 'dirt', description: 'Electro percussion' },
  { name: 'glitch', kind: 'dirt', description: 'Glitch textures and micro-sounds' },
  { name: 'glitch2', kind: 'dirt', description: 'More glitch textures' },
  { name: 'industrial', kind: 'dirt', description: 'Industrial noise hits' },
  { name: 'jungbass', kind: 'dirt', description: 'Jungle/DnB bass stabs' },
  { name: 'jvbass', kind: 'dirt', description: 'JV synth bass notes' },
  { name: 'moog', kind: 'dirt', description: 'Moog bass samples' },
  { name: 'dist', kind: 'dirt', description: 'Distorted sounds' },
  { name: 'stab', kind: 'dirt', description: 'Synth stabs — chord hits' },
  { name: 'hit', kind: 'dirt', description: 'Percussive one-shot hits' },
  { name: 'wobble', kind: 'dirt', description: 'Wobble bass (dubstep-style)' },
  { name: 'hoover', kind: 'dirt', description: 'Hoover bass — rave classic' },
  { name: 'pad', kind: 'dirt', description: 'Pad textures' },
  { name: 'padlong', kind: 'dirt', description: 'Long sustained pads' },
  { name: 'noise', kind: 'dirt', description: 'Noise textures' },
  { name: 'tabla', kind: 'dirt', description: 'Tabla percussion — Indian classical' },
  { name: 'speech', kind: 'dirt', description: 'Speech/vocal chop samples' },
  { name: 'mouth', kind: 'dirt', description: 'Mouth sounds — beatbox, vocal perc' },
  { name: 'sid', kind: 'dirt', description: 'SID chip sounds — 8-bit/chiptune' },
];

export const ALL_SOUNDS: SoundEntry[] = [
  ...DRUMS,
  ...DRUM_BANKS,
  ...SYNTHS,
  ...SAMPLE_LIBRARIES,
  ...GM_INSTRUMENTS,
  ...VCSL_INSTRUMENTS,
  ...DIRT_SAMPLES,
];

export function searchSounds(query: string): SoundEntry[] {
  const q = query.toLowerCase();
  return ALL_SOUNDS.filter(
    (s) => s.name.toLowerCase().includes(q) || s.description.toLowerCase().includes(q),
  );
}
